"""Add enrichment cache tables

Revision ID: 57b0c6d72c46
Revises: f28d5725f53b
Create Date: 2025-11-01 20:09:54.408036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57b0c6d72c46"
down_revision: Union[str, Sequence[str], None] = "f28d5725f53b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actor_profile_cache",
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("account_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_age_days", sa.Integer(), nullable=False),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("following_count", sa.Integer(), nullable=False),
        sa.Column("repository_count", sa.Integer(), nullable=False),
        sa.Column("total_commit_contributions", sa.Integer(), nullable=False),
        sa.Column("total_pr_contributions", sa.Integer(), nullable=False),
        sa.Column("total_issue_contributions", sa.Integer(), nullable=False),
        sa.Column("organizations", sa.Text(), nullable=False),
        sa.Column("is_site_admin", sa.Boolean(), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("login"),
    )
    op.create_index(
        op.f("ix_actor_profile_cache_cached_at"),
        "actor_profile_cache",
        ["cached_at"],
        unique=False,
    )
    op.create_table(
        "commit_verification_cache",
        sa.Column("repository", sa.String(length=300), nullable=False),
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.Column("signer_login", sa.String(length=100), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("changed_files", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=200), nullable=True),
        sa.Column("author_email", sa.String(length=200), nullable=True),
        sa.Column("commit_entropy", sa.Float(), nullable=True),
        sa.Column("commit_size", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("repository", "sha"),
    )
    op.create_index(
        op.f("ix_commit_verification_cache_cached_at"),
        "commit_verification_cache",
        ["cached_at"],
        unique=False,
    )
    op.create_table(
        "repository_context_cache",
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("stargazer_count", sa.Integer(), nullable=False),
        sa.Column("fork_count", sa.Integer(), nullable=False),
        sa.Column("watcher_count", sa.Integer(), nullable=False),
        sa.Column("primary_language", sa.String(length=50), nullable=True),
        sa.Column("default_branch", sa.String(length=100), nullable=True),
        sa.Column("has_security_policy", sa.Boolean(), nullable=False),
        sa.Column("is_fork", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("topics", sa.Text(), nullable=False),
        sa.Column("license_name", sa.String(length=100), nullable=True),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("owner", "name"),
    )
    op.create_index(
        op.f("ix_repository_context_cache_cached_at"),
        "repository_context_cache",
        ["cached_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_context_cache_full_name"),
        "repository_context_cache",
        ["full_name"],
        unique=False,
    )
    op.create_table(
        "workflow_status_cache",
        sa.Column("repository", sa.String(length=300), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("total_check_suites", sa.Integer(), nullable=False),
        sa.Column("successful_suites", sa.Integer(), nullable=False),
        sa.Column("failed_suites", sa.Integer(), nullable=False),
        sa.Column("pending_suites", sa.Integer(), nullable=False),
        sa.Column("check_runs", sa.Text(), nullable=False),
        sa.Column("overall_conclusion", sa.String(length=20), nullable=True),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("repository", "commit_sha"),
    )
    op.create_index(
        op.f("ix_workflow_status_cache_cached_at"),
        "workflow_status_cache",
        ["cached_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_status_cache_cached_at"), table_name="workflow_status_cache"
    )
    op.drop_table("workflow_status_cache")
    op.drop_index(
        op.f("ix_repository_context_cache_full_name"),
        table_name="repository_context_cache",
    )
    op.drop_index(
        op.f("ix_repository_context_cache_cached_at"),
        table_name="repository_context_cache",
    )
    op.drop_table("repository_context_cache")
    op.drop_index(
        op.f("ix_commit_verification_cache_cached_at"),
        table_name="commit_verification_cache",
    )
    op.drop_table("commit_verification_cache")
    op.drop_index(
        op.f("ix_actor_profile_cache_cached_at"), table_name="actor_profile_cache"
    )
    op.drop_table("actor_profile_cache")
    # ### end Alembic commands ###
