"""Initial PostgreSQL schema

Revision ID: f28d5725f53b
Revises: 
Create Date: 2025-11-01 20:08:02.910247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28d5725f53b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_reasoning', sa.String(length=500), nullable=True),
    sa.Column('root_cause', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('suspicious_patterns', sa.JSON(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_login', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=False),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_summaries_actor_login'), 'anomaly_summaries', ['actor_login'], unique=False)
    op.create_index(op.f('ix_anomaly_summaries_created_at'), 'anomaly_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomaly_summaries_event_id'), 'anomaly_summaries', ['event_id'], unique=False)
    op.create_index(op.f('ix_anomaly_summaries_event_timestamp'), 'anomaly_summaries', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_summaries_repo_name'), 'anomaly_summaries', ['repo_name'], unique=False)
    op.create_index(op.f('ix_anomaly_summaries_severity'), 'anomaly_summaries', ['severity'], unique=False)
    op.create_table('github_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_login', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('org_login', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_events_actor_login'), 'github_events', ['actor_login'], unique=False)
    op.create_index(op.f('ix_github_events_created_at'), 'github_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_github_events_event_type'), 'github_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_github_events_is_anomaly'), 'github_events', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_github_events_org_login'), 'github_events', ['org_login'], unique=False)
    op.create_index(op.f('ix_github_events_processed'), 'github_events', ['processed'], unique=False)
    op.create_index(op.f('ix_github_events_repo_name'), 'github_events', ['repo_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_events_repo_name'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_processed'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_org_login'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_is_anomaly'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_event_type'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_created_at'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_actor_login'), table_name='github_events')
    op.drop_table('github_events')
    op.drop_index(op.f('ix_anomaly_summaries_severity'), table_name='anomaly_summaries')
    op.drop_index(op.f('ix_anomaly_summaries_repo_name'), table_name='anomaly_summaries')
    op.drop_index(op.f('ix_anomaly_summaries_event_timestamp'), table_name='anomaly_summaries')
    op.drop_index(op.f('ix_anomaly_summaries_event_id'), table_name='anomaly_summaries')
    op.drop_index(op.f('ix_anomaly_summaries_created_at'), table_name='anomaly_summaries')
    op.drop_index(op.f('ix_anomaly_summaries_actor_login'), table_name='anomaly_summaries')
    op.drop_table('anomaly_summaries')
    # ### end Alembic commands ###
