"""Strongly typed Pydantic models for Server-Sent Events (SSE) messages.

This module defines all SSE message types with full validation and type safety.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class Severity(str, Enum):
    """Severity levels for anomaly detection.

    Enum values ensure type safety and consistent severity classification.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AnomalySummaryResponse(BaseModel):
    """Response model for anomaly summary data sent via SSE.

    This represents the complete anomaly summary with AI-generated analysis,
    detection metadata, and the original GitHub event data.
    """

    id: int = Field(
        description="Unique identifier for this anomaly summary",
        examples=[1, 42],
    )
    event_id: str = Field(
        description="GitHub event ID that triggered this anomaly",
        max_length=50,
        examples=["12345678901"],
    )
    title: str = Field(
        description="Human-readable incident title generated by AI",
        max_length=200,
        examples=["Suspicious Force Push to Main Branch by New Account"],
    )
    severity: Severity = Field(
        description="Severity level of the anomaly",
        examples=[Severity.HIGH],
    )
    severity_reasoning: str = Field(
        description="AI-generated explanation for why this severity level was assigned (1-2 sentences)",
        max_length=500,
        examples=[
            "Classified as HIGH because a newly created account with no contribution history performed a force push to a critical repository's main branch."
        ],
    )
    root_cause: list[str] = Field(
        description="AI-generated root cause analysis (3-5 bullet points)",
        min_length=3,
        max_length=5,
        examples=[
            [
                "Force push detected on protected branch",
                "Actor account created within last 7 days",
                "No previous contribution history",
            ]
        ],
    )
    impact: list[str] = Field(
        description="AI-generated impact assessment (3-5 bullet points)",
        min_length=3,
        max_length=5,
        examples=[
            [
                "Potential code history rewrite",
                "Loss of commit signatures",
                "Risk of malicious code injection",
            ]
        ],
    )
    next_steps: list[str] = Field(
        description="AI-generated recommended actions (3-5 bullet points)",
        min_length=3,
        max_length=5,
        examples=[
            [
                "Review the force-pushed commits immediately",
                "Verify actor identity and authorization",
                "Consider enabling branch protection rules",
            ]
        ],
    )
    suspicious_patterns: list[str] = Field(
        description="Detected anomaly patterns from the detection algorithm",
        examples=[
            [
                "High anomaly score detected",
                "Force push to main branch",
                "New account with high activity",
            ]
        ],
    )
    anomaly_score: float = Field(
        description="Numerical anomaly score from CoDisp algorithm (higher = more anomalous)",
        ge=0.0,
        examples=[8.7, 12.3],
    )
    event_type: str = Field(
        description="GitHub event type",
        max_length=50,
        examples=["PushEvent", "IssuesEvent", "PullRequestEvent"],
    )
    actor_login: str = Field(
        description="GitHub username who triggered the event",
        max_length=100,
        examples=["octocat", "suspicious-user-123"],
    )
    repo_name: str = Field(
        description="Repository name in 'owner/repo' format",
        max_length=200,
        examples=["facebook/react", "torvalds/linux"],
    )
    raw_event: dict[str, Any] = Field(
        description="Complete GitHub Event object with all original data",
        examples=[
            {
                "id": "12345678901",
                "type": "PushEvent",
                "actor": {
                    "id": 583231,
                    "login": "octocat",
                    "display_login": "octocat",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/octocat",
                    "avatar_url": "https://avatars.githubusercontent.com/u/583231",
                },
                "repo": {
                    "id": 1296269,
                    "name": "octocat/Hello-World",
                    "url": "https://api.github.com/repos/octocat/Hello-World",
                },
                "payload": {
                    "repository_id": 1296269,
                    "push_id": 12345678,
                    "ref": "refs/heads/main",
                    "head": "abc123def456",
                    "before": "def456abc123",
                },
                "public": True,
                "created_at": "2025-01-01T12:00:00Z",
            }
        ],
    )
    event_timestamp: datetime = Field(
        description="When the GitHub event occurred (ISO 8601 format)",
        examples=["2025-01-01T12:00:00Z"],
    )
    created_at: datetime = Field(
        description="When this anomaly summary was created (ISO 8601 format)",
        examples=["2025-01-01T12:01:30Z"],
    )
    tags: list[str] = Field(
        description="Classification and security tags",
        examples=[["security", "malicious-activity", "risk:high"]],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "id": 42,
                    "event_id": "12345678901",
                    "title": "Suspicious Force Push to Main Branch by New Account",
                    "severity": "high",
                    "severity_reasoning": "Classified as HIGH because a newly created account with no contribution history performed a force push to a critical repository's main branch.",
                    "root_cause": [
                        "Force push detected on protected branch",
                        "Actor account created within last 7 days",
                        "No previous contribution history",
                    ],
                    "impact": [
                        "Potential code history rewrite",
                        "Loss of commit signatures",
                        "Risk of malicious code injection",
                    ],
                    "next_steps": [
                        "Review the force-pushed commits immediately",
                        "Verify actor identity and authorization",
                        "Consider enabling branch protection rules",
                    ],
                    "suspicious_patterns": [
                        "High anomaly score detected",
                        "Force push to main branch",
                        "New account with high activity",
                    ],
                    "anomaly_score": 12.3,
                    "event_type": "PushEvent",
                    "actor_login": "suspicious-user-123",
                    "repo_name": "acme/critical-infrastructure",
                    "raw_event": {
                        "id": "12345678901",
                        "type": "PushEvent",
                        "actor": {
                            "id": 987654,
                            "login": "suspicious-user-123",
                            "display_login": "suspicious-user-123",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/suspicious-user-123",
                            "avatar_url": "https://avatars.githubusercontent.com/u/987654",
                        },
                        "repo": {
                            "id": 1234567,
                            "name": "acme/critical-infrastructure",
                            "url": "https://api.github.com/repos/acme/critical-infrastructure",
                        },
                        "payload": {
                            "repository_id": 1234567,
                            "push_id": 12345678,
                            "ref": "refs/heads/main",
                            "head": "abc123def456",
                            "before": "def456abc123",
                        },
                        "public": True,
                        "created_at": "2025-01-01T12:00:00Z",
                    },
                    "event_timestamp": "2025-01-01T12:00:00Z",
                    "created_at": "2025-01-01T12:01:30Z",
                    "tags": ["security", "malicious-activity", "risk:high"],
                }
            ]
        }
    }


class SSEMessageBase(BaseModel):
    """Base model for all SSE messages with discriminator."""

    type: str = Field(description="Message type discriminator")


class ConnectedMessage(SSEMessageBase):
    """Initial connection acknowledgment message sent when SSE stream is established."""

    type: Literal["connected"] = Field(
        default="connected",
        description="Message type discriminator",
    )
    message: str = Field(
        default="Stream connected",
        description="Connection confirmation message",
        examples=["Stream connected"],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [{"type": "connected", "message": "Stream connected"}]
        }
    }


class AnomalyMessage(SSEMessageBase):
    """Real-time anomaly notification message containing a complete anomaly summary."""

    type: Literal["anomaly"] = Field(
        default="anomaly",
        description="Message type discriminator",
    )
    data: AnomalySummaryResponse = Field(
        description="Complete anomaly summary with AI analysis and event data",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "type": "anomaly",
                    "data": {
                        "id": 42,
                        "event_id": "12345678901",
                        "title": "Suspicious Force Push to Main Branch by New Account",
                        "severity": "high",
                        "severity_reasoning": "Classified as HIGH because a newly created account with no contribution history performed a force push to a critical repository's main branch.",
                        "root_cause": [
                            "Force push detected on protected branch",
                            "Actor account created within last 7 days",
                            "No previous contribution history",
                        ],
                        "impact": [
                            "Potential code history rewrite",
                            "Loss of commit signatures",
                            "Risk of malicious code injection",
                        ],
                        "next_steps": [
                            "Review the force-pushed commits immediately",
                            "Verify actor identity and authorization",
                            "Consider enabling branch protection rules",
                        ],
                        "suspicious_patterns": [
                            "High anomaly score detected",
                            "Force push to main branch",
                            "New account with high activity",
                        ],
                        "anomaly_score": 12.3,
                        "event_type": "PushEvent",
                        "actor_login": "suspicious-user-123",
                        "repo_name": "acme/critical-infrastructure",
                        "raw_event": {
                            "id": "12345678901",
                            "type": "PushEvent",
                            "actor": {"id": 987654, "login": "suspicious-user-123"},
                            "repo": {
                                "id": 1234567,
                                "name": "acme/critical-infrastructure",
                            },
                            "payload": {"ref": "refs/heads/main"},
                            "public": True,
                            "created_at": "2025-01-01T12:00:00Z",
                        },
                        "event_timestamp": "2025-01-01T12:00:00Z",
                        "created_at": "2025-01-01T12:01:30Z",
                        "tags": ["security", "malicious-activity", "risk:high"],
                    },
                }
            ]
        }
    }


# Union type for all possible SSE messages
SSEMessage = ConnectedMessage | AnomalyMessage
